#!/bin/bash

if [ "${MUNIN_DEBUG:-0}" = 1 ]; then
    set -x
fi

BACKUP_DIR=${backup_dir:-/backups}
LIFETIME=${lifetime:-2}

case $1 in
    config)
        cat <<EOF
graph_title Fresh files
graph_info Number of fresh (<=$LIFETIME days old) updated files in $BACKUP_DIR
graph_args -l 0
graph_category backup
graph_vlabel freshcount
freshcount.label Files fresher than $LIFETIME days old
EOF
        exit 0;;
esac

TOTAL=0
if [ $(date +%M) == 00 ]; then
    for path in "$BACKUP_DIR"/*; do
        if [ -d $path ]; then
            DIR="${path}/current"

            if [ -d $DIR ]; then
                COUNT=$(find "${DIR}/" -mtime "-${LIFETIME}" | wc -l)
                TOTAL=$(($TOTAL+$COUNT))
                echo "${TOTAL}" > "${BACKUP_DIR}/count"
            fi
        fi
    done
else
    if [ -f "${BACKUP_DIR}/count" ]; then
        TOTAL=$(<"${BACKUP_DIR}/count")
    fi
fi

echo "freshcount.value ${TOTAL}"
