#!/bin/bash

if [ "${MUNIN_DEBUG:-0}" = 1 ]; then
    set -x
fi

BACKUP_DIR=${backup_dir:-/backups}
LIFETIME=${lifetime:-2}

case $1 in
    config)
        cat <<EOF
graph_title Fresh files
graph_info Number of fresh (<=$LIFETIME days old) updated files in $BACKUP_DIR
graph_args -l 0
graph_category backup
graph_vlabel freshcount
freshcount.label Files fresher than $LIFETIME days old
EOF
        exit 0;;
esac

TOTAL=0
for path in "$BACKUP_DIR"/*; do
    if [ -d $path ]; then
        DIR="${path}/current"

        if [ -d $DIR ]; then
            COUNT=$(find "${DIR}/" -mtime "-${LIFETIME}" | wc -l)
            TOTAL=$(($TOTAL+$COUNT))
        fi
    fi
done

echo "freshcount.value ${TOTAL}"